name: CI 

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env: 
      NIXTLA_API_KEY: ${{ secrets.NIXTLA_API_KEY }}
      TIMESCALE_DBNAME: ${{ secrets.TIMESCALE_DBNAME }}
      TIMESCALE_HOST: ${{ secrets.TIMESCALE_HOST }}
      TIMESCALE_PASSWORD: ${{ secrets.TIMESCALE_PASSWORD }}
      TIMESCALE_PORT: ${{ secrets.TIMESCALE_PORT }}
      TIMESCALE_USERNAME: ${{ secrets.TIMESCALE_USERNAME }}
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Set up Python
        uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # 5.2.0
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install uv && uv pip install -e . --system

      - name: Run tests 
        run: pytest --cov 
